# Generated by Django 4.1.3 on 2023-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.ImageField(upload_to='media')),
                ('aadhar_card', models.ImageField(upload_to='mdeia')),
            ],
        ),
    ]
