# Generated by Django 4.1.3 on 2023-03-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='aadhar_card',
            field=models.ImageField(upload_to='media'),
        ),
    ]
