# Generated by Django 4.1.3 on 2022-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('work_experience', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=100)),
                ('certificates', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('intrests', models.CharField(max_length=100)),
            ],
        ),
    ]
