# Generated by Django 4.1.3 on 2023-02-27 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='a',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='a',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
