# Generated by Django 4.1.3 on 2023-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('s_no', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('Father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
