# Generated by Django 4.1.3 on 2023-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='s_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
