# Generated by Django 4.1.3 on 2022-12-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Odisha', 'Bhubaneswar'), ('Punjab', 'Chandigarh'), ('Rajasthan', 'Jaipur'), ('Sikkim', 'Gangtok'), ('Tamil Nadu', 'Chennai'), ('Telangana', 'Hyderabad'), ('Tripura', 'Agartala'), ('Uttar Pradesh', 'Lucknow'), ('Uttarakhand', '\tDehradun Winter'), ('Gairsain', 'Summer'), ('West', 'Bengal')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
